import { Sale } from "@/lib/google/types";

export function saleMessage(sale: Sale) {
  return `🛒 ShopFlow

Hello ${sale.customer},

Thank you for shopping with us!

━━━━━━━━━━━━━━━━━━

📦 Jaggery : ${sale.jaggeryKg} kg
🍵 Tea Powder : ${sale.teaKg} kg

💰 Total : ₹${sale.total}
💳 Payment : ${sale.paymentStatus}

━━━━━━━━━━━━━━━━━━

We appreciate your business.

Have a great day! 🙏`;
}

export function paymentReminderMessage(
  customer: string,
  amount: number
) {
  return `💰 Payment Reminder

Hello ${customer},

This is a friendly reminder that ₹${amount} is still pending.

Kindly complete the payment at your earliest convenience.

Thank you 🙏`;
}

export function dailyReportMessage(
  totalSales: number,
  revenue: number,
  paid: number,
  credit: number
) {
  return `📊 ShopFlow Daily Report

🛒 Sales: ${totalSales}
💰 Revenue: ₹${revenue}
✅ Paid: ₹${paid}
🟥 Credit: ₹${credit}

Generated by ShopFlow 🤖`;
}